openapi: 3.0.1
info:
  title: NIC Code Suggestion API
  description: API for suggesting NIC codes based on detailed business context
  version: "1.0"
paths:
  /api/suggest:
    post:
      summary: Submit business context and get NIC suggestions directly
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                business_details:
                  type: string
                  description: Detailed business description
      responses:
        "200":
          description: NIC code suggestions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  nic_codes:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        description:
                          type: string
        "500":
            description: Internal server error

  /api/feedback:
    post:
      summary: Submit user feedback on NIC code satisfaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                satisfied:
                  type: boolean
                additional_info:
                  type: string
                  description: Optional context for dissatisfaction
      responses:
        "200":
          description: Feedback received successfully
